### ISSUE TITLE
Admin: Zobrazit datum vložení nabídky na BE

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-contember#14]
Všechny 3 typy Uživatelů BE   mohou u všech Nabídek vidět nove pole Datum vložení nabídky - pod Stav

![image](https://user-images.githubusercontent.com/101886400/161190979-db914927-a8a8-49b7-aee1-ea2a10b3c654.png)

**Comment by ZdenekMen** [comment]
Ahoj Martine @VanaMartin , koukam, ze je to in review.  Prosim te, neceka to na mne?

**Comment by ZdenekMen** [comment]
Ahoj Martine, @VanaMartin , dekuji moc, obrazovka vypadá dobře. 

 Koukám, že je tam všude stejné - dnešní datum. Prosím tě, to nikde není v databázi uložené datum, kdy tam byla Nabídka založena? děkuji

**Comment by honzasladek** [comment]
Ten čas je uložený u Volunteer (taky createdAt), z toho by to šlo vzít

**Comment by honzasladek** [comment]
Asi nejsnazší je nasadit tuhle verzi a pak udělat sql dotaz, co to překopiruje. Jestli souhlas @ZdenekMen , tak zařídím

**Comment by ZdenekMen** [comment]
@honzasladek Ahoj Honzo, ze jsi to ty a ja ti verim, ze to zaridis  tj bude tam opravdu puvodni datum zalozeni nabikdy ,  tak OK DEKUJI VSEM.

**Comment by ZdenekMen** [comment]
@honzasladek , Ahoj Honzo, prosim te, stale je tam a v Provozu :-( to fixni vcerejsi datum. Ja myslel, ze to nejak opravis - viz vyse. Dekuji moc

**Comment by honzasladek** [comment]
Hmm, to, že mergujeme neschválené věci do mainu není dobrý. Nasadil to tam kolega spolu se stejnýma úpravama. Chtěl jsem to teď jít nasadit a ty data tam nakopírovat. Tak už zbývá jen ta část tam dát data...

**Comment by ZdenekMen** [comment]
@honzasladek dekuji, promin, ja jsme asi spatne pochopil tu tvoji zpravu, ze se to nasadi a hned nejak opravi

**Comment by honzasladek** [comment]
Jo, to byl plán. :) Akorát ta oprava musela proběhnout ručně. Už je to hotové @ZdenekMen
