### ISSUE TITLE
Admin: Seznam dobrovolníků v BE: mohly by být vidět jejich typy nabídek? 

### ISSUE THREAD

**Issue by ZdenekMen** [cesko-digital/pomahejukrajine-contember#19]
Uživatel BE si zobrazí seznam dobrovolníků, někdy se stává, že je tam určitý dobrovolník vícekrát, (lidi jsou tam třeba 3x, a nevíme, ke kterému ze záznamů patří jaké nabídky). 

V orientaci by  pomohlo , pokud by se v seznamu ukázaly typy  jednotlivých nabídek (zalomeně) Např “Administrativní pomoc v institucích”,  “Materiální pomoc”, atd 

![image](https://user-images.githubusercontent.com/101886400/163143030-44bdeee0-3cce-4a39-927f-47b21baea0d7.png)

**Comment by ZdenekMen** [comment]
Ahoj Martine @VanaMartin , koukam, ze je to in review.  Prosim te, neceka to na mne?

**Comment by VanaMartin** [comment]
Ted uz ano, kod jsem dnes sloucil

**Comment by honzasladek** [comment]
(Bylo špatně pořadí migrací, opravil jsem a je to nasazené na betě.)

**Comment by ZdenekMen** [comment]
Ahoj Martine, @VanaMartin , perfektni, dekuji
 @honzasladek  Honzo, prosim te, muzes to dat do Produkce ?
dekuji vsem

**Comment by honzasladek** [comment]
Je to už pár dnů nasazené v produkci, tak zavírám.
