### ISSUE TITLE
Admin: Datumová pole pro ubytování - možnost zadávat, editovat jak je ubytování v čase k dispozici

### ISSUE THREAD

**Issue by Michal-Miky-Jankovsky** [cesko-digital/pomahejukrajine-contember#9]
naklikat a administraci

blocker for https://github.com/cesko-digital/pomahejukrajine-web/issues/41

**Comment by george-cz** [comment]
Closing dupe of https://github.com/cesko-digital/pomahejukrajine-contember/issues/13
